version: "3.8"

services:
  vitaledge-open-llm:
    build: .
    container_name: vitaledge-open-llm
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    volumes:
      - .:/app
